### ISSUE TITLE
Arduino Nano RP2040 Connect Support Request

### ISSUE THREAD

**Issue by SuperJonotron** [Picovoice/picovoice-arduino-en#1]
It looks like at the core of this project, it should be able to drop directly into the RP2040 ecosystem, specifically around the connect since it also utilizes a build in microphone using the same PDM libraries the 33 BLE Sense uses.

As a compile test only (don't have a RP2040 connect currently), I was able to add the define headers to support both the open source and the official RP2040 board referenced from here: https://forum.arduino.cc/t/raspberry-pi-pico-variant-name/866778

#if defined(ARDUINO_ARDUINO_NANO33BLE) || defined(ARDUINO_ARCH_SAMD) || defined(ARDUINO_ARCH_MBED_RP2040) || defined(ARDUINO_ARCH_RP2040)

This opens the code to compile against the RP2040 boards but still hit an issue on the pre-compiled library.  

To further test this, I just created a folder for the expected location for the RP2040 architecture by copying the existing compiled library src/cortex-m4 to src/cortex-m0plus.  This allows compiling against the RP2040 connect board in the Arduino IDE without issue.  I know this is likely to fail if I had a board to upload to because I tricked the IDE to use a pre-compiled library for a wrong architecture but it was more of a "let's see what happens" situation.

If it's possible to pre-compile the libpicovoice code for the cortex-m0plus architecture, this should be all it takes to make it compatible which would then add direct IoT capability to the Arduino and picovoice world.

**Comment by mrrostam** [comment]
You are right about the compilation and the whole Arduino ecosystem, but the Picovoice engine is not suitable for RP2040 as is, and needs some engineering effort to optimize it for this architecture.

Let's keep this open and see what kind of traction we get from the community.
