### ISSUE TITLE
Arduino Nano 33 BLE Sense Pin Config and External Clock

### ISSUE THREAD

**Issue by johnkelton** [Picovoice/picovoice-arduino-en#11]
I was successfully able to run the PicovoiceExcample on my arduino. Now I want to reassign the pins to an external pdm audio stream. So bascially instead of using a PDM input from the builtin microphone on the Arduino Nano 33  BLE Sense board, I want to input an audio stream (PDM) from an external source (a microcontroller). The clock will also be refenced from the external source. How can I reassign the pins and also make my clock line to be input to the Arduino nano 33 BLE Sense? 

Thanks a lot for any help!

**Comment by laves** [comment]
I'd suggest reaching out to Arduino support to determine how to do this. This forum is to address issues regarding the Picovoice SDK only.

**Comment by johnkelton** [comment]
Thanks for your response. Can you help me understand the boundary of Picovoice SDK? I mean , the SDK only responsible for processing the audio signal? What is the expectation of the SDK for the audio stream? Thanks
