### ISSUE TITLE
Wake Word bypass or delay

### ISSUE THREAD

**Issue by zumatt** [Picovoice/picovoice-arduino-en#13]
Hi,

I would like to know if it is possible to add a feature that bypasses the wakeword and directly starts checking for expressions. Alternatively, it would be helpful to create a delay after the user intent in order to facilitate a dialogue between the voice assistant and the user.

Thank you.

**Comment by mrrostam** [comment]
Hi there,

Unfortunately, there is no way to bypass the wake word detection step in the [Picovoice SDK](https://github.com/Picovoice/picovoice) as switching happens internally and we have no control over it. What you need is [Rhino](https://github.com/Picovoice/rhino) alone, for which we don't have an Arduino/MCU port yet as its usability is limited.

Regarding the delay, you can simply skip passing a few audio frames after the callback.
