### ISSUE TITLE
Support for multiple wake words

### ISSUE THREAD

**Issue by jakebierman** [Picovoice/picovoice-arduino-en#15]
Hi, is there any way to get multiple wake words working? I am using a portenta H7 and this appears to be supported in porcupine-arduino-en. would be nice to spupport a wake_world_callback which has a keyword_index paramater similar to what was done in the porcupine example or possibly take an array of callback functions.
The reasone for asking here when its possible already in porcupine is because that will have to work with Rhino to also use intents but rhino is not currently supported on arduino

**Comment by kenarsa** [comment]
You are correct. The Picovoice SDK abstraction allows one wake word, and we will prob keep this abstraction as it serves 99% of use cases. Rhino MCU SDK is available only to enterprise customers. If you have an account manager feel free to reach out to them directly for more information
