### ISSUE TITLE
Issues with example code for Arduino Nano

### ISSUE THREAD

**Issue by johnbon** [Picovoice/picovoice-arduino-en#6]
Hi,

I am trying to test out the original Arduino sample code for the Nano BLE Sense, however I keep receiving a note during compiling stating that I am missing a pre-compiled library which is shown in the first picture attached. While it does still compile, when opening the serial monitor I am met with the "Invalid Argument" as shown in the second picture. I have the most up to date version of the library. If anyone has any ideas I would greatly appreciate the feedback!
![Invalid Output](https://user-images.githubusercontent.com/13153483/144887042-93a6b799-b169-460f-943d-a4a14913b138.PNG)
![Missing File](https://user-images.githubusercontent.com/13153483/144887046-543d0be7-be2a-46f1-a681-352579fb28eb.PNG)

**Comment by mrrostam** [comment]
That missing pre-compiled library is ok as it falls back to a more generic "cortex-m4" one.
My guess is that you're using an invalid [AccessKey](https://console.picovoice.ai/access_key). Can you double check it again to make sure that the input `AccessKey` is correct?

**Comment by johnbon** [comment]
After a few attempts at changing around the output it did work thank you for the quick response! I was going based off the label on the Picovoice website which is what threw me off. Thanks again!

**Comment by mrrostam** [comment]
No problem. Regarding the mentioned label on our website, can you guide me to it?

**Comment by johnbon** [comment]
The link to the page is: https://picovoice.ai/docs/quick-start/picovoice-arduino/

In the photo I attached, I highlighted the depiction as to how to insert access key, however in order for it to work it should just be 

ACCESS_KEY = "ACESS KEY";

![Access Key](https://user-images.githubusercontent.com/13153483/144910519-a79a03d6-f99e-4347-89fc-2c567fff8e3a.PNG)
