### ISSUE TITLE
Control_LED_Picovoice demo compile issue

### ISSUE THREAD

**Issue by jackieken** [Picovoice/picovoice-arduino-en#9]
Hi,
I would like to try Control_LED_Picovoice demo for "Arduino Nano 33 BLE".
I have failed the compile with the error messages as follows:
If you have any advice, please let me know. 

Arduino：1.8.19 (Windows Store 1.8.57.0) (Windows 10), ボード："Arduino Nano 33 BLE"
C:\Users\ユーザー\OneDrive\デスクトップ\\Control_LED_Picovoice.ino: In function 'void setup()':
Control_LED_Picovoice:10:32: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
C:\Users\ユーザー\OneDrive\デスクトップ\Control_LED_Picovoice\Control_LED_Picovoice.ino:170:13: note: in expansion of macro 'MEMORY_BUFFER_SIZE'
Control_LED_Picovoice:180:20: error: invalid conversion from 'int8_t* {aka signed char*}' to 'int32_t {aka long int}' [-fpermissive]
Control_LED_Picovoice:172:19: error: invalid conversion from 'unsigned int' to 'void*' [-fpermissive]
Control_LED_Picovoice:180:20: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'int32_t {aka long int}' [-fpermissive]
Control_LED_Picovoice:180:20: error: cannot convert 'const float' to 'const void*' for argument '5' to 'pv_status_t pv_picovoice_init(const char*, int32_t, void*, int32_t, const void*, float, void (*)(), int32_t, const void*, float, bool, void (*)(pv_inference_t*), pv_picovoice_t**)'
exit status 1
invalid conversion from 'int' to 'const char*' [-fpermissive]

**Comment by mrrostam** [comment]
Thank you for reporting this @jackieken. The LED demo on the Arduino Cloud is out of date. I'll let you know when it's updated to use the latest Picovoice package.

**Comment by mrrostam** [comment]
The [LED demo](https://create.arduino.cc/editor/dynamix91/7dae06f6-b827-4b20-ad00-b1558ae1b98c/preview) is updated. Please ensure you're using the latest Picovoice library (v2.1.1). Also don't forget to put your AccessKey inside the main sketch. For more information, refer to the [Arduino doc](https://picovoice.ai/docs/quick-start/picovoice-arduino/) on our website.

**Comment by jackieken** [comment]
Thank you for your advice. 
I have updated LED demo and Picovoice library.
Finally I have completed the compilation of demo.
I appreciate your help.
